import { type NextPage } from "next";
import Head from "next/head";

export default function BookAppointmentPage() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-center">
          <iframe
            className="scrollable-iframe h-[80vh] w-[66vw]"
            id="bookingIframe"
            src="https://booking.setmore.com/scheduleappointment/7dcf47c6-5071-446a-9687-0f95c8a402ad"
          />
        </div>
      </main>
    </>
  );
}
