import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import SectionWithImage from "@/components/SectionWithImage";
import { MailingListForm } from "@/components/MailingListForm";
import Hero from "@/components/Hero";
import FAQAccordian from "@/components/FAQAccordian";
import siteConfig from "@/site.config";

const content =
  "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique architecto animi error, sit rerum illo fugit aperiam, modi debitis nisi est. Exercitationem rerum nihil eaque";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Hero />
        <FAQAccordian />
        <SectionWithImage
          displayTitle={false}
          title="first-section"
          img={siteConfig.heroImg}
          content={content}
          style="dark"
          imgPosition="left"
          displayBGPattern={true}
        />
        <MailingListForm style="light" />
      </main>
    </>
  );
};

export default Home;
