import { type NextPage } from "next";
import Head from "next/head";
import Hero from "@/components/Hero";
import { MailingListForm } from "@/components/MailingListForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <MailingListForm />
      </main>
    </>
  );
};

export default Home;
