import { type NextPage } from "next";
import Head from "next/head";
import Hero from "@/components/Hero";
import { MailingListForm } from "@/components/MailingListForm";
import FAQAccordian from "@/components/FAQAccordian";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className="container flex min-h-screen max-w-7xl flex-col">
        <FAQAccordian />
        <MailingListForm />
      </main>
    </>
  );
};

export default Home;
